language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t breakingpitt/elasticsearch elasticsearch
  - docker build -t breakingpitt/firefox firefox
  - docker build -t breakingpitt/kafka apache-kafka
  - docker build -t breakingpitt/rethinkdb rethinkdb

